apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: nginx
    targetRevision: 18.3.1
    helm:
      releaseName: nginx
      values: |
        image:
          registry: docker.io
          repository: bitnami/nginx
          tag: latest
        replicaCount: 2
        service:
          type: ClusterIP
        tolerations:
          - effect: NoExecute
            key: no-worker
            operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
