apiVersion: v1
kind: Service
metadata:
  name: gop-code
  labels:
    app: gop-code
spec:
  type: ClusterIP
  selector:
    app: gop-code
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
