apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://matheusfm.dev/charts
    chart: httpbin
    targetRevision: 0.1.1
    helm:
      releaseName: httpbin
      values: |
        tolerations:
          - effect: NoExecute
            key: no-worker
            operator: Exists
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
